# Generated by Django 5.0.6 on 2026-05-08 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cooperative',
            field=models.ForeignKey(blank=True, db_column='cooperativeId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='cooperatives.cooperative'),
        ),
    ]
