# Generated by Django 5.0.6 on 2026-05-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_cooperative'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(db_column='isEmailVerified', default=False),
        ),
    ]
