# Generated by Django 5.0.6 on 2026-04-28 08:11

import django.db.models.deletion
import sensors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseDetection',
            fields=[
                ('id', models.CharField(default=sensors.models._generate_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('image_url', models.TextField(db_column='imageUrl')),
                ('result', models.TextField()),
                ('confidence', models.FloatField()),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_column='detectedAt')),
                ('notes', models.TextField(blank=True, null=True)),
                ('batch', models.ForeignKey(db_column='batchId', on_delete=django.db.models.deletion.CASCADE, related_name='disease_detections', to='batches.batch')),
            ],
            options={
                'db_table': 'disease_detections',
                'indexes': [models.Index(fields=['batch'], name='disease_batch_idx')],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.CharField(default=sensors.models._generate_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(db_column='batchId', on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to='batches.batch')),
            ],
            options={
                'db_table': 'sensor_readings',
                'indexes': [models.Index(fields=['batch'], name='sensor_batch_idx'), models.Index(fields=['timestamp'], name='sensor_timestamp_idx')],
            },
        ),
    ]
