# Generated by Django 5.0.6 on 2026-04-28 08:11

import batches.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.CharField(default=batches.models._generate_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('EGG', 'Egg'), ('LARVA', 'Larva'), ('PUPA', 'Pupa'), ('COCOON', 'Cocoon'), ('HARVEST', 'Harvest')], default='EGG', max_length=10)),
                ('start_date', models.DateTimeField(auto_now_add=True, db_column='startDate')),
                ('expected_harvest_date', models.DateTimeField(db_column='expectedHarvestDate')),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_column='isActive', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('farm', models.ForeignKey(db_column='farmId', on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='farms.farm')),
            ],
            options={
                'db_table': 'batches',
                'indexes': [models.Index(fields=['farm'], name='batches_farm_idx'), models.Index(fields=['stage'], name='batches_stage_idx')],
            },
        ),
    ]
