# Generated by Django 5.0.6 on 2026-04-28 08:11

import alerts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.CharField(default=alerts.models._generate_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('TEMPERATURE', 'Temperature'), ('HUMIDITY', 'Humidity'), ('DISEASE', 'Disease'), ('STAGE_CHANGE', 'Stage Change'), ('SYSTEM', 'System')], max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_column='isRead', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('batch', models.ForeignKey(db_column='batchId', on_delete=django.db.models.deletion.CASCADE, related_name='alert_logs', to='batches.batch')),
            ],
            options={
                'db_table': 'alert_logs',
                'indexes': [models.Index(fields=['batch'], name='alert_batch_idx'), models.Index(fields=['is_read'], name='alert_is_read_idx')],
            },
        ),
    ]
