# Generated by Django 5.0.6 on 2026-05-09 15:17

import django.db.models.deletion
import harvest.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestRecord',
            fields=[
                ('id', models.CharField(default=harvest.models._generate_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('cocoon_weight_kg', models.DecimalField(db_column='cocoonWeightKg', decimal_places=2, max_digits=8)),
                ('silk_yield_g', models.DecimalField(blank=True, db_column='silkYieldG', decimal_places=2, max_digits=8, null=True)),
                ('quality_grade', models.CharField(choices=[('A', 'Grade A — Premium'), ('B', 'Grade B — Standard'), ('C', 'Grade C — Below standard')], db_column='qualityGrade', default='A', max_length=1)),
                ('notes', models.TextField(blank=True, null=True)),
                ('harvested_at', models.DateTimeField(auto_now_add=True, db_column='harvestedAt')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('batch', models.ForeignKey(db_column='batchId', on_delete=django.db.models.deletion.CASCADE, related_name='harvest_records', to='batches.batch')),
            ],
            options={
                'db_table': 'harvest_records',
                'ordering': ['-harvested_at'],
            },
        ),
    ]
