# Generated by Django 5.0.6 on 2026-04-28 08:11

import django.db.models.deletion
import farms.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.CharField(default=farms.models._generate_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=250)),
                ('is_active', models.BooleanField(db_column='isActive', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('owner', models.ForeignKey(db_column='ownerId', on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'farms',
                'indexes': [models.Index(fields=['owner'], name='farms_owner_idx')],
            },
        ),
    ]
